{% set name = "repytah" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/repytah-{{ version }}.tar.gz
  sha256: a4b7e1c1634d007572e4af036fde67cf6f098839664f79bbfebded2f9b2993be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7,<4.0
    - numpy >=1.21.6
    - scipy >=1.7.3
    - pandas >=1.3.5
    - matplotlib-base >=3.3.4
    - opencv >=4.5.0
    - setuptools >=61.2.0

test:
  imports:
    - repytah
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smith-tinkerlab/repytah
  summary: Python package for building Aligned Hierarchies for sequential data streams
  dev_url: https://github.com/smith-tinkerlab/repytah
  doc_url: https://repytah.readthedocs.io/
  license: ISC
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kmkinnaird
